import PDFDocument from 'pdfkit';

/** Host-facing match fee invoice PDF. Edit layout and copy here; data is assembled in PaymentsService.buildHostReceiptPdf. */
export type MatchFeeReceiptData = {
  invoiceId: string;
  invoiceNumber: string;
  issuedAt: Date;
  paidAt: Date | null;
  dueAt: Date;
  /** Match fee before HST. */
  amountCents: number;
  taxCents: number;
  taxRateLabel: string;
  /** Total refunded so far, including HST. */
  refundedCents: number;
  hstRegistrationNumber: string | null;
  currency: string;
  status: string;
  jobTitle: string;
  postingScheduleLabel: string | null;
  postingLocation: string | null;
  locumName: string;
  /** When set, this locum replaced the original confirmed locum. */
  replacedByLocumName?: string | null;
  practiceName: string;
  hostEmail: string;
  paymentProvider: string;
  paymentReference: string | null;
};

function formatMoney(amountCents: number, currency: string): string {
  return `$${(amountCents / 100).toFixed(2)} ${currency}`;
}

function formatDate(d: Date): string {
  return d.toLocaleDateString('en-CA', { timeZone: 'UTC' });
}

export async function buildMatchFeeReceiptPdf(
  data: MatchFeeReceiptData,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'LETTER' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('LocumLink');
    doc.fontSize(11).fillColor('#444').text('Match fee receipt');
    doc.moveDown(0.5);
    doc.fillColor('#000');

    doc.fontSize(10).text(`Receipt # ${data.invoiceNumber}`);
    if (data.hstRegistrationNumber) {
      doc.text(`HST registration: ${data.hstRegistrationNumber}`);
    }
    doc.text(`Invoice ID: ${data.invoiceId}`);
    doc.text(`Issued: ${formatDate(data.issuedAt)}`);
    doc.text(`Due: ${formatDate(data.dueAt)}`);
    if (data.paidAt) {
      doc.text(`Paid: ${formatDate(data.paidAt)}`);
    }
    doc.text(`Status: ${data.status.replace(/_/g, ' ')}`);
    doc.moveDown();

    doc.fontSize(12).text('Bill to', { underline: true });
    doc.fontSize(10).text(data.practiceName);
    doc.text(data.hostEmail);
    doc.moveDown();

    doc.fontSize(12).text('Match details', { underline: true });
    doc.fontSize(10).text(`Posting: ${data.jobTitle}`);
    if (data.postingScheduleLabel) {
      doc.text(`Shifts: ${data.postingScheduleLabel}`);
    }
    if (data.postingLocation) {
      doc.text(`Location: ${data.postingLocation}`);
    }
    doc.text(`Confirmed locum: ${data.locumName}`);
    if (data.replacedByLocumName) {
      doc.text(
        `Replacement: ${data.replacedByLocumName} replaced ${data.locumName}`,
      );
    }
    doc.moveDown();

    doc.fontSize(12).text('Amount', { underline: true });
    const totalCents = data.amountCents + data.taxCents;
    if (data.taxCents > 0) {
      doc.fontSize(10).text(`Match fee: ${formatMoney(data.amountCents, data.currency)}`);
      doc.text(`HST (${data.taxRateLabel}): ${formatMoney(data.taxCents, data.currency)}`);
      doc.fontSize(14).text(`Total: ${formatMoney(totalCents, data.currency)}`);
    } else {
      doc.fontSize(14).text(formatMoney(totalCents, data.currency));
    }
    if (data.refundedCents > 0) {
      doc.fontSize(10).text(`Refunded: ${formatMoney(data.refundedCents, data.currency)}`);
    }
    doc.fontSize(10).text(
      'LocumLink platform match fee (not clinical pay). MSI pays the locum directly for clinical work.',
    );
    doc.moveDown();

    doc.fontSize(12).text('Payment', { underline: true });
    doc.fontSize(10).text(`Method: ${data.paymentProvider}`);
    if (data.paymentReference) {
      doc.text(`Reference: ${data.paymentReference}`);
    }

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#666').text(
      'Questions: support@locumlink.ca - This document is generated by LocumLink for your records.',
    );

    doc.end();
  });
}
